
import json
import os

file_path = '/home/omar/Desktop/aman/frontend/src/locales/ar.json'

new_manufacturing = {
    "title": "التصنيع",
    "dashboard": {
      "title": "لوحة التصنيع",
      "subtitle": "إدارة عمليات التصنيع والإنتاج",
      "total_orders": "إجمالي الأوامر",
      "in_progress": "قيد التنفيذ",
      "completed": "مكتملة",
      "completed_orders": "الأوامر المكتملة",
      "active_boms": "قوائم المواد النشطة",
      "production_30d": "الإنتاج (آخر 30 يومًا)",
      "production_volume_30d": "حجم الإنتاج (30 يوم)",
      "material_cost_30d": "تكلفة المواد (آخر 30 يومًا)",
      "recent_orders": "أوامر الإنتاج الأخيرة",
      "recently_completed": "الأوامر المكتملة مؤخراً",
      "view_all_orders": "عرض جميع الأوامر",
      "view_boms": "عرض قوائم المواد",
      "no_recent_orders": "لا توجد أوامر حديثة",
      "no_completed_orders": "لا توجد أوامر مكتملة",
      "overview": "نظرة عامة",
      "no_data_yet": "ستظهر تفاصيل لوحة معلومات الإنتاج هنا قريباً"
    },
    "status": {
      "draft": "مسودة",
      "in_progress": "قيد التنفيذ",
      "completed": "مكتمل",
      "cancelled": "ملغي"
    },
    "details": {
      "title": "أمر إنتاج",
      "order_info": "معلومات الأمر",
      "order_number": "رقم الأمر",
      "bom_name": "قائمة المواد",
      "product_name": "المنتج النهائي",
      "created_date": "تاريخ الإنشاء",
      "start_date": "تاريخ البدء",
      "end_date": "تاريخ الانتهاء",
      "completion_date": "تاريخ الإتمام",
      "cost_breakdown": "تحليل التكلفة",
      "material_cost": "تكلفة المواد",
      "labor_cost": "تكلفة العمالة",
      "overhead_cost": "التكاليف العامة",
      "total_cost": "التكلفة الكلية",
      "total_material_cost": "إجمالي تكلفة المواد",
      "unit_cost": "تكلفة الوحدة",
      "unit_cost_label": "سعر الوحدة",
      "bom_qty": "كمية BOM",
      "total_needed": "الكمية المطلوبة",
      "line_cost": "التكلفة",
      "available": "المتوفر",
      "material_count": "عدد المواد الخام",
      "raw_materials_table": "جدول المواد الخام",
      "material": "المادة",
      "required_qty": "الكمية المطلوبة",
      "available_stock": "المخزون المتاح",
      "sufficient": "كافي",
      "insufficient": "غير كافي",
      "insufficient_materials": "المواد الخام غير كافية",
      "materials_warning": "⚠️ بعض المواد الخام غير كافية في المخزون. لا يمكن إتمام الإنتاج.",
      "stock_status": "حالة المخزون",
      "inventory_movements": "حركات المخزون",
      "movement_type": "نوع الحركة",
      "output_type": "إنتاج",
      "consume_type": "استهلاك",
      "quantity": "الكمية",
      "date": "التاريخ",
      "consumption": "استهلاك",
      "production": "إنتاج",
      "confirm_start": "هل تريد بدء أمر التصنيع هذا؟",
      "confirm_cancel": "تأكيد الإلغاء",
      "confirm_complete": "تأكيد الإتمام",
      "complete_confirm": "سيتم خصم المواد الخام من المخزون وإضافة المنتج النهائي. هل أنت متأكد؟",
      "started": "تم بدء أمر الإنتاج",
      "cancelled": "تم إلغاء أمر الإنتاج",
      "order_started": "تم بدء أمر التصنيع",
      "order_cancelled": "تم إلغاء أمر التصنيع",
      "not_found": "أمر الإنتاج غير موجود",
      "load_error": "فشل في تحميل أمر الإنتاج",
      "back_to_list": "العودة للقائمة",
      "back_to_orders": "العودة للأوامر",
      "start_order": "بدء الأمر",
      "cancel_order": "إلغاء الأمر",
      "cancel_title": "إلغاء أمر الإنتاج",
      "complete_order": "إتمام الأمر"
    },
    "production_orders": "أوامر التصنيع",
    "production_orders_desc": "إدارة وتنفيذ أوامر الإنتاج",
    "new_order": "أمر تصنيع جديد",
    "new_order_desc": "إنشاء أمر تصنيع جديد",
    "active_orders": "أوامر قيد التنفيذ",
    "completed_orders": "أوامر مكتملة",
    "manage_orders": "إدارة أوامر التصنيع",
    "manage_work_centers": "إدارة محطات العمل",
    "manage_routes": "إدارة المسارات",
    "manage_boms": "إدارة قوائم المواد",
    "recent_orders": "أحدث أوامر التصنيع",
    "no_orders": "لا توجد أوامر تصنيع حالياً",
    "orders_tab_desc": "عرض وإدارة جميع أوامر التصنيع الحالية والسابقة",
    "go_to_orders": "الذهاب إلى صفحة الأوامر",
    "no_orders_found": "لم يتم العثور على أوامر تصنيع",
    "work_centers": "محطات العمل",
    "work_centers_desc": "إدارة مواقع التصنيع والتكاليف",
    "add_work_center": "إضافة محطة عمل",
    "edit_work_center": "تعديل محطة عمل",
    "capacity_costs": "السعة والتكاليف",
    "accounting_integration": "الربط المحاسبي",
    "overhead_account": "حساب التكاليف الإضافية",
    "wc_location": "الموقع",
    "wc_cost_center": "مركز التكلفة",
    "wc_overhead_account": "حساب المصاريف غير المباشرة",
    "wc_status": "الحالة",
    "daily_capacity": "السعة اليومية (ساعات)",
    "wc_cost_per_hour": "التكلفة / ساعة",
    "routings": "مسارات التصنيع",
    "routings_desc": "تعريف عمليات الإنتاج",
    "add_routing": "إضافة مسار",
    "edit_route": "تعديل مسار",
    "route_name": "اسم المسار",
    "finished_product": "المنتج النهائي",
    "operations": "العمليات",
    "operations_sequence": "تسلسل العمليات",
    "work_center": "محطة العمل",
    "setup_time": "وقت التحضير (دقيقة)",
    "cycle_time": "وقت التشغيل (دقيقة)",
    "run_time": "تشغيل",
    "bom_title": "قوائم المواد (BOM)",
    "bom_desc": "إدارة وصفات المنتجات",
    "bom_list": "قوائم المواد",
    "new_bom": "قائمة مواد جديدة",
    "add_bom": "إضافة قائمة مواد",
    "edit_bom": "تعديل قائمة مواد",
    "bom_name": "اسم القائمة",
    "bom_code": "الكود/الإصدار",
    "bom": "قائمة المواد",
    "select_bom": "اختر قائمة المواد",
    "select_bom_required": "يجب اختيار قائمة المواد",
    "no_boms_available": "لا توجد قوائم مواد متاحة. قم بإنشاء قائمة مواد أولاً.",
    "routing": "المسار",
    "default_route": "المسار الافتراضي",
    "yield_quantity": "كمية الإنتاج المتوقعة",
    "components": "المكونات / المواد الخام",
    "component": "المكون",
    "qty": "الكمية",
    "quantity": "الكمية المطلوبة",
    "waste_pct": "نسبة الهالك %",
    "cost_share_pct": "نسبة مشاركة التكلفة %",
    "raw_materials_source": "مصدر المواد الخام",
    "finished_goods_destination": "وجهة المنتج النهائي",
    "recent_activity": "النشاط الأخير",
    "finish": "إنهاء",
    "start_production": "بدء الإنتاج",
    "complete_production": "إتمام الإنتاج",
    "product": "المنتج النهائي",
    "materials": "المواد الخام",
    "add_material": "إضافة مادة",
    "material_name": "اسم المادة",
    "material_quantity": "الكمية المطلوبة",
    "unit": "الوحدة",
    "output_quantity": "كمية الإنتاج",
    "output": "المخرجات",
    "cycles": "عدد الدورات",
    "total_output": "إجمالي الإنتاج",
    "order_created": "تم إنشاء أمر التصنيع بنجاح",
    "production_details": "تفاصيل الإنتاج",
    "production_details_desc": "حدد قائمة المواد والكمية المطلوبة",
    "no_orders_desc": "لم يتم إنشاء أي أوامر تصنيع بعد",
    "confirm_complete": "هل أنت متأكد من إتمام أمر التصنيع؟",
    "order_completed": "تم إتمام أمر التصنيع بنجاح",
    "add_item": "إضافة صنف",
    "item": "الصنف",
    "raw_materials": "المواد الخام",
    "waste": "الهالك"
}

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

data['manufacturing'] = new_manufacturing

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully updated ar.json")
