"""
SEC-301: SQL Safety Utilities
Validation for SQL identifiers and parameterized query helpers.
Prevents SQL injection in DDL statements and dynamic queries.
"""
import re
import logging

logger = logging.getLogger("aman.sql_safety")

# Pattern: alphanumeric + underscore only, starting with letter or underscore
_IDENTIFIER_PATTERN = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')
# Pattern for database/user names generated by AMAN (e.g., aman_abc123, company_abc123)
_AMAN_IDENTIFIER_PATTERN = re.compile(r'^[a-z0-9_]+$')


def validate_sql_identifier(name: str, label: str = "identifier") -> str:
    """
    Validate that a string is a safe SQL identifier.
    Raises ValueError if the name contains dangerous characters.
    
    Args:
        name: The identifier to validate
        label: Human-readable label for error messages
    
    Returns:
        The validated name (unchanged)
    """
    if not name or not isinstance(name, str):
        raise ValueError(f"Invalid {label}: empty or non-string")
    
    if len(name) > 128:
        raise ValueError(f"Invalid {label}: too long (max 128 chars)")
    
    if not _IDENTIFIER_PATTERN.match(name):
        raise ValueError(
            f"Invalid {label} '{name}': must contain only letters, numbers, and underscores, "
            f"starting with a letter or underscore"
        )
    
    # Block SQL keywords as identifiers
    SQL_KEYWORDS = {
        'select', 'insert', 'update', 'delete', 'drop', 'create', 'alter',
        'truncate', 'grant', 'revoke', 'union', 'where', 'from', 'table',
        'database', 'user', 'password', 'exec', 'execute'
    }
    if name.lower() in SQL_KEYWORDS:
        raise ValueError(f"Invalid {label}: '{name}' is a reserved SQL keyword")
    
    return name


def validate_aman_identifier(name: str, label: str = "identifier") -> str:
    """
    Validate AMAN-generated identifiers (database names, user names).
    These follow the pattern: aman_<hex> or company_<hex>
    
    Args:
        name: The identifier to validate
        label: Human-readable label for error messages
    
    Returns:
        The validated name (unchanged)
    """
    if not name or not isinstance(name, str):
        raise ValueError(f"Invalid {label}: empty or non-string")
    
    if len(name) > 128:
        raise ValueError(f"Invalid {label}: too long (max 128 chars)")
    
    if not _AMAN_IDENTIFIER_PATTERN.match(name):
        raise ValueError(
            f"Invalid {label} '{name}': must contain only lowercase letters, numbers, and underscores"
        )
    
    return name


def validate_password_strength(password: str) -> None:
    """
    SEC-302: Validate password meets security requirements.
    Raises HTTPException if password is too weak.
    
    Requirements:
    - Minimum 10 characters
    - At least one uppercase letter  
    - At least one lowercase letter
    - At least one digit
    - At least one special character
    """
    from fastapi import HTTPException
    
    if len(password) < 10:
        raise HTTPException(400, "كلمة المرور يجب أن تكون 10 أحرف على الأقل")
    if not re.search(r'[A-Z]', password):
        raise HTTPException(400, "كلمة المرور يجب أن تحتوي على حرف كبير واحد على الأقل")
    if not re.search(r'[a-z]', password):
        raise HTTPException(400, "كلمة المرور يجب أن تحتوي على حرف صغير واحد على الأقل")
    if not re.search(r'[0-9]', password):
        raise HTTPException(400, "كلمة المرور يجب أن تحتوي على رقم واحد على الأقل")
    if not re.search(r'[^A-Za-z0-9]', password):
        raise HTTPException(400, "كلمة المرور يجب أن تحتوي على رمز خاص واحد على الأقل (!@#$%^&*)")


# File upload security constants
MAX_DOCUMENT_SIZE = 50 * 1024 * 1024  # 50 MB
MAX_IMPORT_FILE_SIZE = 10 * 1024 * 1024  # 10 MB
MAX_LOGO_SIZE = 5 * 1024 * 1024  # 5 MB

BLOCKED_FILE_EXTENSIONS = {
    '.exe', '.bat', '.cmd', '.sh', '.php', '.jsp', '.py', '.rb',
    '.pl', '.cgi', '.com', '.scr', '.pif', '.vbs', '.js', '.ws',
    '.wsf', '.msi', '.dll', '.sys', '.drv', '.ps1', '.psm1'
}

ALLOWED_IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp', '.bmp'}
ALLOWED_IMPORT_EXTENSIONS = {'.csv', '.xlsx', '.xls'}
ALLOWED_DOCUMENT_EXTENSIONS = {
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
    '.txt', '.csv', '.jpg', '.jpeg', '.png', '.gif', '.svg',
    '.zip', '.rar', '.7z'
}


def validate_file_size(content: bytes, max_size: int, label: str = "الملف") -> None:
    """Validate uploaded file doesn't exceed maximum size"""
    from fastapi import HTTPException
    if len(content) > max_size:
        max_mb = max_size / (1024 * 1024)
        raise HTTPException(413, f"حجم {label} يتجاوز الحد الأقصى المسموح ({max_mb:.0f} ميجابايت)")


def validate_file_extension(filename: str, allowed: set = None, label: str = "الملف") -> str:
    """
    Validate file extension is safe.
    
    Args:
        filename: The original filename
        allowed: Set of allowed extensions (if None, just blocks dangerous ones)
        label: Human-readable label for error messages
    
    Returns:
        The file extension (lowercase)
    """
    import os
    from fastapi import HTTPException
    
    if not filename:
        raise HTTPException(400, f"اسم {label} مطلوب")
    
    ext = os.path.splitext(filename)[1].lower()
    
    # Always block dangerous extensions
    if ext in BLOCKED_FILE_EXTENSIONS:
        raise HTTPException(400, f"نوع {label} غير مسموح ({ext})")
    
    # If allowed set provided, check against it
    if allowed and ext not in allowed:
        raise HTTPException(400, f"نوع {label} غير مدعوم ({ext}). الأنواع المسموحة: {', '.join(sorted(allowed))}")
    
    return ext


def validate_file_path_safety(file_path: str, base_dir: str) -> bool:
    """
    Validate that a file path is within the expected base directory.
    Prevents path traversal attacks.
    
    Returns True if safe, False if potentially malicious.
    """
    import os
    abs_path = os.path.abspath(file_path)
    abs_base = os.path.abspath(base_dir)
    return abs_path.startswith(abs_base + os.sep) or abs_path == abs_base
