import uuid
import requests

try:
    from testsprite_tests._helpers import BASE_URL, TIMEOUT, USERNAME, PASSWORD, COMPANY_CODE, login_and_get_token, auth_headers, get_json
except ModuleNotFoundError:
    from _helpers import BASE_URL, TIMEOUT, USERNAME, PASSWORD, COMPANY_CODE, login_and_get_token, auth_headers, get_json


def tc001_login_success():
    token = login_and_get_token()
    assert isinstance(token, str) and len(token) > 20


def tc002_login_invalid_credentials():
    response = requests.post(
        f"{BASE_URL}/api/auth/login",
        data={"username": USERNAME, "password": "wrong-password-123", "company_code": COMPANY_CODE},
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        timeout=TIMEOUT,
    )
    assert response.status_code in (401, 429), f"Expected 401/429, got {response.status_code}: {response.text}"


def tc_auth_refresh_success():
    token = login_and_get_token()
    response = requests.post(
        f"{BASE_URL}/api/auth/refresh",
        headers={"Authorization": f"Bearer {token}"},
        timeout=TIMEOUT,
    )
    assert response.status_code == 200, f"Refresh failed: {response.status_code} {response.text}"
    payload = get_json(response)
    assert payload.get("token_type", "").lower() == "bearer"
    assert payload.get("access_token")


def tc_companies_authorized_access():
    response = requests.get(
        f"{BASE_URL}/api/companies/list",
        headers=auth_headers(),
        timeout=TIMEOUT,
    )
    assert response.status_code == 200, f"Companies list failed: {response.status_code} {response.text}"
    payload = get_json(response)
    assert isinstance(payload, dict)
    assert "items" in payload and isinstance(payload["items"], list)


def tc_companies_unauthorized_access():
    response = requests.get(f"{BASE_URL}/api/companies/list", timeout=TIMEOUT)
    assert response.status_code in (401, 403), f"Expected 401/403, got {response.status_code}: {response.text}"


def tc_roles_create_with_permissions():
    headers = auth_headers()
    role_name = f"testsprite_role_{uuid.uuid4().hex[:8]}"
    response = requests.post(
        f"{BASE_URL}/api/roles",
        headers={**headers, "Content-Type": "application/json"},
        json={
            "role_name": role_name,
            "description": "Generated by TestSprite",
            "permissions": ["reports.view"],
        },
        timeout=TIMEOUT,
    )
    assert response.status_code == 201, f"Role creation failed: {response.status_code} {response.text}"
    payload = get_json(response)
    role_id = payload.get("id")
    assert role_id is not None

    requests.delete(f"{BASE_URL}/api/roles/{role_id}", headers=headers, timeout=TIMEOUT)


def tc_roles_create_without_admin_permission_rejected():
    response = requests.post(
        f"{BASE_URL}/api/roles",
        headers={"Authorization": "Bearer invalid-token", "Content-Type": "application/json"},
        json={"role_name": "forbidden_role", "permissions": ["reports.view"]},
        timeout=TIMEOUT,
    )
    assert response.status_code in (401, 403), f"Expected 401/403, got {response.status_code}: {response.text}"


def tc_accounting_entries_date_range():
    response = requests.get(
        f"{BASE_URL}/api/accounting/journal-entries",
        headers=auth_headers(),
        params={"date_from": "2026-01-01", "date_to": "2026-12-31", "page": 1, "limit": 20},
        timeout=TIMEOUT,
    )
    assert response.status_code == 200, f"Journal entries failed: {response.status_code} {response.text}"
    payload = get_json(response)
    assert isinstance(payload, dict)
    assert "items" in payload and isinstance(payload["items"], list)


def tc_treasury_transfer_create():
    headers = auth_headers()
    accounts_response = requests.get(f"{BASE_URL}/api/treasury/accounts", headers=headers, timeout=TIMEOUT)
    assert accounts_response.status_code == 200, f"Accounts list failed: {accounts_response.status_code} {accounts_response.text}"
    accounts = get_json(accounts_response)
    assert isinstance(accounts, list)

    if len(accounts) < 2:
        return

    src_id = accounts[0]["id"]
    dst_id = accounts[1]["id"]
    if src_id == dst_id:
        return

    response = requests.post(
        f"{BASE_URL}/api/treasury/transactions/transfer",
        headers={**headers, "Content-Type": "application/json"},
        json={
            "transaction_date": "2026-03-01",
            "transaction_type": "transfer",
            "amount": 1.0,
            "treasury_id": src_id,
            "target_treasury_id": dst_id,
            "description": "TestSprite transfer test",
            "exchange_rate": 1.0,
        },
        timeout=TIMEOUT,
    )
    assert response.status_code == 201, f"Transfer failed: {response.status_code} {response.text}"


def tc_treasury_transfer_reject_same_account():
    headers = auth_headers()
    accounts_response = requests.get(f"{BASE_URL}/api/treasury/accounts", headers=headers, timeout=TIMEOUT)
    assert accounts_response.status_code == 200, f"Accounts list failed: {accounts_response.status_code} {accounts_response.text}"
    accounts = get_json(accounts_response)
    assert isinstance(accounts, list)
    if not accounts:
        return

    acc_id = accounts[0]["id"]
    response = requests.post(
        f"{BASE_URL}/api/treasury/transactions/transfer",
        headers={**headers, "Content-Type": "application/json"},
        json={
            "transaction_date": "2026-01-15",
            "transaction_type": "transfer",
            "amount": 1.0,
            "treasury_id": acc_id,
            "target_treasury_id": acc_id,
            "description": "Invalid self transfer",
            "exchange_rate": 1.0,
        },
        timeout=TIMEOUT,
    )
    assert response.status_code in (400, 422), f"Expected 400/422, got {response.status_code}: {response.text}"


def tc_sales_orders_open_status():
    response = requests.get(
        f"{BASE_URL}/api/sales/orders",
        headers=auth_headers(),
        params={"status": "open"},
        timeout=TIMEOUT,
    )
    assert response.status_code == 200, f"Sales orders failed: {response.status_code} {response.text}"
    payload = get_json(response)
    assert isinstance(payload, list)


def tc_purchases_orders_create():
    headers = auth_headers()

    suppliers_resp = requests.get(f"{BASE_URL}/api/inventory/suppliers", headers=headers, timeout=TIMEOUT)
    assert suppliers_resp.status_code == 200, f"Suppliers list failed: {suppliers_resp.status_code} {suppliers_resp.text}"
    suppliers = get_json(suppliers_resp)
    assert isinstance(suppliers, list)

    if suppliers:
        supplier_id = suppliers[0]["id"]
    else:
        new_supplier_resp = requests.post(
            f"{BASE_URL}/api/inventory/suppliers",
            headers={**headers, "Content-Type": "application/json"},
            json={"name": f"TestSprite Supplier {uuid.uuid4().hex[:6]}", "currency": "SAR", "branch_id": 1},
            timeout=TIMEOUT,
        )
        assert new_supplier_resp.status_code in (200, 201), f"Supplier create failed: {new_supplier_resp.status_code} {new_supplier_resp.text}"
        supplier_id = get_json(new_supplier_resp)["id"]

    po_resp = requests.post(
        f"{BASE_URL}/api/buying/orders",
        headers={**headers, "Content-Type": "application/json"},
        json={
            "supplier_id": supplier_id,
            "order_date": "2026-03-01",
            "branch_id": 1,
            "currency": "SAR",
            "items": [
                {
                    "product_id": None,
                    "description": "TestSprite PO line",
                    "quantity": 1,
                    "unit_price": 10,
                    "tax_rate": 0,
                    "discount": 0,
                }
            ],
        },
        timeout=TIMEOUT,
    )
    assert po_resp.status_code == 201, f"Purchase order creation failed: {po_resp.status_code} {po_resp.text}"


def tc_root_backend_response():
    response = requests.get(f"{BASE_URL}/", timeout=TIMEOUT)
    assert response.status_code == 200, f"Root failed: {response.status_code} {response.text}"
    content_type = response.headers.get("Content-Type", "")
    assert "application/json" in content_type.lower(), f"Expected JSON root response, got {content_type}"


def tc_api_docs_access():
    response = requests.get(f"{BASE_URL}/api/docs", timeout=TIMEOUT)
    assert response.status_code == 200, f"Docs failed: {response.status_code} {response.text}"
    body = response.text.lower()
    assert "swagger" in body or "openapi" in body
