"""phase1_models_autogen_draft

Revision ID: da58152b4322
Revises: 0003_je_trigger_hard
Create Date: 2026-03-30 16:18:49.234543
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision: str = 'da58152b4322'
down_revision: Union[str, None] = '0003_je_trigger_hard'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
