"""Central ORM model exports.

Developer guidance:
- Prefer domain-first discovery under backend.models.domains for new work.
- Phase files remain as compatibility/history from incremental rollout.
- Keep this module as the stable export surface for legacy imports.
"""

from .base import ModelBase
from .business_core import (
    CompanySetting,
    Invoice,
    InvoiceLine,
    Party,
    PartyGroup,
    TreasuryAccount,
    UserBranch,
    Warehouse,
)
from .core_accounting import Account, Branch, CompanyUser, JournalEntry, JournalLine
from .phase2_ops_hr import (
    Attendance,
    Department,
    Employee,
    EmployeeLoan,
    EmployeePosition,
    EmployeeSalaryComponent,
    Inventory,
    InventoryTransaction,
    LeaveRequest,
    PayrollEntry,
    PayrollPeriod,
    Product,
    ProductCategory,
    ProductUnit,
    PurchaseOrder,
    PurchaseOrderLine,
    SalaryComponent,
    SalaryStructure,
    StockAdjustment,
)
from .phase3_treasury_tax_projects import (
    BankReconciliation,
    BankStatementLine,
    BranchTaxSetting,
    CompanyTaxSetting,
    Project,
    ProjectBudget,
    ProjectChangeOrder,
    ProjectDocument,
    ProjectExpense,
    ProjectRevenue,
    ProjectTask,
    TaxGroup,
    TaxPayment,
    TaxRate,
    TaxRegime,
    TaxReturn,
    TreasuryTransaction,
)
from .phase4_operations_support import (
    CheckPayable,
    CheckReceivable,
    Document,
    DocumentVersion,
    Expense,
    NotePayable,
    NoteReceivable,
    ServiceRequest,
    ServiceRequestCost,
    SupportTicket,
    TicketComment,
)
from .phase6_approvals import ApprovalAction, ApprovalRequest, ApprovalWorkflow
from .phase7_assets_core import Asset, AssetCategory, AssetTransfer
from .phase8_budgets_core import Budget, BudgetItem, BudgetLine
from .phase9_costing_core import (
    CostCenter,
    CostCenterBudget,
    CostingPolicy,
    CostingPolicyDetail,
    CostingPolicyHistory,
    InventoryCostSnapshot,
)
from .phase10_assets_advanced import (
    AssetDepreciationSchedule,
    AssetDisposal,
    AssetImpairment,
    AssetInsurance,
    AssetMaintenance,
    AssetRevaluation,
)
from .phase11_currency_bank_import import BankImportBatch, BankImportLine, Currency, ExchangeRate
from .phase12_fiscal_zakat import FiscalPeriodLock, FiscalYear, ZakatCalculation
from .phase13_contracts_expenses import Contract, ContractItem, ExpensePolicy
from .phase14_crm_advanced import (
    CrmCustomerSegment,
    CrmCustomerSegmentMember,
    CrmLeadScore,
    CrmLeadScoringRule,
    CrmSalesForecast,
)
from .phase15_ops_security_reporting import ApiKey, AuditLog, BackupHistory, CustomReport, EmailTemplate
from .phase16_inventory_bins_cycle import (
    BatchSerialMovement,
    BinInventory,
    BinLocation,
    CycleCount,
    CycleCountItem,
)
from .phase17_inventory_variants_kits import (
    ProductAttribute,
    ProductAttributeValue,
    ProductKit,
    ProductVariant,
    ProductVariantAttribute,
)
from .phase18_inventory_traceability_quality import (
    ProductBatch,
    ProductKitItem,
    ProductSerial,
    QualityInspection,
    QualityInspectionCriteria,
)
from .phase19_customer_master_pricing import (
    Customer,
    CustomerBankAccount,
    CustomerContact,
    CustomerPriceList,
    CustomerPriceListItem,
)
from .phase20_receivables_delivery import (
    CustomerBalance,
    CustomerReceipt,
    CustomerTransaction,
    DeliveryOrder,
    DeliveryOrderLine,
)
from .phase21_hr_compliance_recruitment import (
    EmployeeCustody,
    EmployeeDocument,
    EmployeeViolation,
    JobApplication,
    JobOpening,
)
from .phase22_mfg_attachments_commissions import (
    Attachment,
    BillOfMaterial,
    BomOutput,
    CheckStatusLog,
    CommissionRule,
)
from .phase23_reporting_documents_fx_crm import (
    CrmContact,
    CurrencyTransaction,
    DocumentTemplate,
    DocumentType,
    FinancialReport,
)
from .phase24_mfg_capacity_contracts_crm_groups import (
    BomComponent,
    CapacityPlan,
    ContractAmendment,
    CrmKnowledgeBase,
    CustomerGroup,
)
from .phase25_dashboard_fiscal_gosi_intercompany_landed_costs import (
    DashboardLayout,
    FiscalPeriod,
    GosiSetting,
    IntercompanyTransaction,
    LandedCostAllocation,
)
from .domain_models.finance_cashflow import (
    PartyTransaction,
    Payment,
    PaymentAllocation,
    PaymentVoucher,
    RecurringJournalLine,
    RecurringJournalTemplate,
)
from .domain_models.finance_forecast import CashFlowForecast, CashFlowForecastLine
from .domain_models.finance_recognition_tax import RevenueRecognitionSchedule, TaxCalendar, WhtRate, WhtTransaction
from .domain_models.hr_training import TrainingParticipant, TrainingProgram
from .domain_models.hr_workforce import LeaveCarryover, OvertimeRequest, PerformanceReview
from .domain_models.inventory_transfers import StockShipment, StockShipmentItem, StockTransferLog
from .domain_models.manufacturing_execution import (
    ManufacturingEquipment,
    ManufacturingOperation,
    ManufacturingRoute,
    MfgQcCheck,
    MrpItem,
    MrpPlan,
    ProductionOrder,
    ProductionOrderOperation,
)
from .domain_models.manufacturing_resources import WorkCenter
from .domain_models.operations_support import LeaseContract, MaintenanceLog, MarketingCampaign
from .domain_models.procurement_costs import (
    LandedCost,
    LandedCostItem,
    PendingPayable,
    PurchaseAgreement,
    PurchaseAgreementLine,
)
from .domain_models.procurement_suppliers import (
    Supplier,
    SupplierBalance,
    SupplierBankAccount,
    SupplierContact,
    SupplierGroup,
    SupplierPayment,
    SupplierRating,
    SupplierTransaction,
)
from .domain_models.projects_dependencies import TaskDependency
from .domain_models.projects_execution import OpportunityActivity, ProjectRisk, ProjectTimesheet
from .domain_models.sales_pos import (
    PendingReceivable,
    PosKitchenOrder,
    PosLoyaltyPoint,
    PosLoyaltyProgram,
    PosLoyaltyTransaction,
    PosOrder,
    PosOrderLine,
    PosOrderPayment,
    PosPayment,
    PosPromotion,
    PosReturn,
    PosReturnItem,
    PosSession,
    PosTable,
    PosTableOrder,
    Receipt,
)
from .domain_models.sales_rfq import (
    RequestForQuotation,
    RfqLine,
    RfqResponse,
    SalesCommission,
    SalesOpportunity,
    SalesOrder,
    SalesOrderLine,
    SalesQuotation,
    SalesQuotationLine,
    SalesReturn,
    SalesReturnLine,
    SalesTarget,
)
from .domain_models.security_comms import LoginAttempt, Message, Notification, PasswordHistory, PrintTemplate, ReportTemplate
from .domain_models.security_reporting import (
    Role,
    ScheduledReport,
    SecurityEvent,
    SharedReport,
    User2FASetting,
    UserSession,
    WebhookLog,
    Webhook,
)
from .domain_models.intercompany import EntityGroup, IntercompanyTransactionV2, IntercompanyAccountMapping
from .domain_models.inventory_costing import CostLayer, CostLayerConsumption
from .domain_models.matching import MatchTolerance, ThreeWayMatch, ThreeWayMatchLine
from .domain_models.self_service import SelfServiceRequest
from .domain_models.sso import SsoConfiguration, SsoGroupRoleMapping, SsoFallbackAdmin


target_metadata = ModelBase.metadata
MODELED_TABLES = set(target_metadata.tables.keys())

__all__ = [
    "ModelBase",
    "UserBranch",
    "PartyGroup",
    "Party",
    "TreasuryAccount",
    "Warehouse",
    "Invoice",
    "InvoiceLine",
    "CompanySetting",
    "CompanyUser",
    "Branch",
    "Account",
    "JournalEntry",
    "JournalLine",
    "ProductCategory",
    "ProductUnit",
    "Product",
    "Inventory",
    "InventoryTransaction",
    "StockAdjustment",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "PayrollPeriod",
    "Department",
    "EmployeePosition",
    "Employee",
    "Attendance",
    "EmployeeLoan",
    "LeaveRequest",
    "SalaryStructure",
    "SalaryComponent",
    "EmployeeSalaryComponent",
    "PayrollEntry",
    "TreasuryTransaction",
    "BankReconciliation",
    "BankStatementLine",
    "TaxRate",
    "TaxGroup",
    "TaxReturn",
    "TaxPayment",
    "TaxRegime",
    "BranchTaxSetting",
    "CompanyTaxSetting",
    "Project",
    "ProjectTask",
    "ProjectBudget",
    "ProjectExpense",
    "ProjectRevenue",
    "ProjectDocument",
    "ProjectChangeOrder",
    "CheckReceivable",
    "CheckPayable",
    "NoteReceivable",
    "NotePayable",
    "Expense",
    "ServiceRequest",
    "ServiceRequestCost",
    "Document",
    "DocumentVersion",
    "SupportTicket",
    "TicketComment",
    "ApprovalWorkflow",
    "ApprovalRequest",
    "ApprovalAction",
    "AssetCategory",
    "Asset",
    "AssetTransfer",
    "Budget",
    "BudgetItem",
    "BudgetLine",
    "CostCenter",
    "CostCenterBudget",
    "CostingPolicy",
    "CostingPolicyDetail",
    "CostingPolicyHistory",
    "InventoryCostSnapshot",
    "AssetDepreciationSchedule",
    "AssetDisposal",
    "AssetRevaluation",
    "AssetInsurance",
    "AssetMaintenance",
    "AssetImpairment",
    "Currency",
    "ExchangeRate",
    "BankImportBatch",
    "BankImportLine",
    "FiscalYear",
    "FiscalPeriodLock",
    "ZakatCalculation",
    "Contract",
    "ContractItem",
    "ExpensePolicy",
    "CrmLeadScoringRule",
    "CrmLeadScore",
    "CrmCustomerSegment",
    "CrmCustomerSegmentMember",
    "CrmSalesForecast",
    "ApiKey",
    "AuditLog",
    "BackupHistory",
    "CustomReport",
    "EmailTemplate",
    "BatchSerialMovement",
    "CycleCount",
    "CycleCountItem",
    "BinLocation",
    "BinInventory",
    "ProductAttribute",
    "ProductAttributeValue",
    "ProductVariant",
    "ProductVariantAttribute",
    "ProductKit",
    "ProductBatch",
    "ProductSerial",
    "QualityInspection",
    "QualityInspectionCriteria",
    "ProductKitItem",
    "Customer",
    "CustomerContact",
    "CustomerBankAccount",
    "CustomerPriceList",
    "CustomerPriceListItem",
    "CustomerTransaction",
    "CustomerReceipt",
    "CustomerBalance",
    "DeliveryOrder",
    "DeliveryOrderLine",
    "EmployeeDocument",
    "EmployeeViolation",
    "EmployeeCustody",
    "JobOpening",
    "JobApplication",
    "Attachment",
    "BillOfMaterial",
    "BomOutput",
    "CheckStatusLog",
    "CommissionRule",
    "FinancialReport",
    "DocumentType",
    "DocumentTemplate",
    "CurrencyTransaction",
    "CrmContact",
    "BomComponent",
    "CapacityPlan",
    "CashFlowForecast",
    "CashFlowForecastLine",
    "ContractAmendment",
    "CrmKnowledgeBase",
    "CustomerGroup",
    "DashboardLayout",
    "FiscalPeriod",
    "GosiSetting",
    "IntercompanyTransaction",
    "LandedCostAllocation",
    "LandedCost",
    "LandedCostItem",
    "LeaseContract",
    "LeaveCarryover",
    "LoginAttempt",
    "MaintenanceLog",
    "ManufacturingEquipment",
    "ManufacturingOperation",
    "ManufacturingRoute",
    "MarketingCampaign",
    "Message",
    "MfgQcCheck",
    "MrpItem",
    "MrpPlan",
    "Notification",
    "OpportunityActivity",
    "OvertimeRequest",
    "PartyTransaction",
    "PasswordHistory",
    "PaymentAllocation",
    "PaymentVoucher",
    "Payment",
    "PendingPayable",
    "PendingReceivable",
    "PerformanceReview",
    "PosKitchenOrder",
    "PosLoyaltyPoint",
    "PosLoyaltyProgram",
    "PosLoyaltyTransaction",
    "PosOrderLine",
    "PosOrderPayment",
    "PosOrder",
    "PosPayment",
    "PosPromotion",
    "PosReturnItem",
    "PosReturn",
    "PosSession",
    "PosTableOrder",
    "PosTable",
    "PrintTemplate",
    "ProductionOrderOperation",
    "ProductionOrder",
    "ProjectRisk",
    "ProjectTimesheet",
    "PurchaseAgreementLine",
    "PurchaseAgreement",
    "Receipt",
    "RecurringJournalLine",
    "RecurringJournalTemplate",
    "ReportTemplate",
    "RequestForQuotation",
    "RevenueRecognitionSchedule",
    "RfqLine",
    "RfqResponse",
    "Role",
    "SalesCommission",
    "SalesOpportunity",
    "SalesOrderLine",
    "SalesOrder",
    "SalesQuotationLine",
    "SalesQuotation",
    "SalesReturnLine",
    "SalesReturn",
    "SalesTarget",
    "ScheduledReport",
    "SecurityEvent",
    "SharedReport",
    "StockShipmentItem",
    "StockShipment",
    "StockTransferLog",
    "SupplierBalance",
    "SupplierBankAccount",
    "SupplierContact",
    "SupplierGroup",
    "SupplierPayment",
    "SupplierRating",
    "SupplierTransaction",
    "Supplier",
    "TaskDependency",
    "TaxCalendar",
    "TrainingParticipant",
    "TrainingProgram",
    "User2FASetting",
    "UserSession",
    "WebhookLog",
    "Webhook",
    "WhtRate",
    "WhtTransaction",
    "WorkCenter",
    # Phase 2 domain models
    "CostLayer",
    "CostLayerConsumption",
    "EntityGroup",
    "IntercompanyAccountMapping",
    "IntercompanyTransactionV2",
    "MatchTolerance",
    "SelfServiceRequest",
    "SsoConfiguration",
    "SsoFallbackAdmin",
    "SsoGroupRoleMapping",
    "ThreeWayMatch",
    "ThreeWayMatchLine",
    "target_metadata",
    "MODELED_TABLES",
]
