from .base import ModelBase
from .business_core import (
    CompanySetting,
    Invoice,
    InvoiceLine,
    Party,
    PartyGroup,
    TreasuryAccount,
    UserBranch,
    Warehouse,
)
from .core_accounting import Account, Branch, CompanyUser, JournalEntry, JournalLine
from .phase2_ops_hr import (
    Attendance,
    Department,
    Employee,
    EmployeeLoan,
    EmployeePosition,
    EmployeeSalaryComponent,
    Inventory,
    InventoryTransaction,
    LeaveRequest,
    PayrollEntry,
    PayrollPeriod,
    Product,
    ProductCategory,
    ProductUnit,
    PurchaseOrder,
    PurchaseOrderLine,
    SalaryComponent,
    SalaryStructure,
    StockAdjustment,
)
from .phase3_treasury_tax_projects import (
    BankReconciliation,
    BankStatementLine,
    BranchTaxSetting,
    CompanyTaxSetting,
    Project,
    ProjectBudget,
    ProjectChangeOrder,
    ProjectDocument,
    ProjectExpense,
    ProjectRevenue,
    ProjectTask,
    TaxGroup,
    TaxPayment,
    TaxRate,
    TaxRegime,
    TaxReturn,
    TreasuryTransaction,
)
from .phase4_operations_support import (
    CheckPayable,
    CheckReceivable,
    Document,
    DocumentVersion,
    Expense,
    NotePayable,
    NoteReceivable,
    ServiceRequest,
    ServiceRequestCost,
    SupportTicket,
    TicketComment,
)
from .phase6_approvals import ApprovalAction, ApprovalRequest, ApprovalWorkflow
from .phase7_assets_core import Asset, AssetCategory, AssetTransfer
from .phase8_budgets_core import Budget, BudgetItem, BudgetLine
from .phase9_costing_core import (
    CostCenter,
    CostCenterBudget,
    CostingPolicy,
    CostingPolicyDetail,
    CostingPolicyHistory,
    InventoryCostSnapshot,
)
from .phase10_assets_advanced import (
    AssetDepreciationSchedule,
    AssetDisposal,
    AssetImpairment,
    AssetInsurance,
    AssetMaintenance,
    AssetRevaluation,
)
from .phase11_currency_bank_import import BankImportBatch, BankImportLine, Currency, ExchangeRate
from .phase12_fiscal_zakat import FiscalPeriodLock, FiscalYear, ZakatCalculation
from .phase13_contracts_expenses import Contract, ContractItem, ExpensePolicy
from .phase14_crm_advanced import (
    CrmCustomerSegment,
    CrmCustomerSegmentMember,
    CrmLeadScore,
    CrmLeadScoringRule,
    CrmSalesForecast,
)
from .phase15_ops_security_reporting import ApiKey, AuditLog, BackupHistory, CustomReport, EmailTemplate
from .phase16_inventory_bins_cycle import (
    BatchSerialMovement,
    BinInventory,
    BinLocation,
    CycleCount,
    CycleCountItem,
)
from .phase17_inventory_variants_kits import (
    ProductAttribute,
    ProductAttributeValue,
    ProductKit,
    ProductVariant,
    ProductVariantAttribute,
)
from .phase18_inventory_traceability_quality import (
    ProductBatch,
    ProductKitItem,
    ProductSerial,
    QualityInspection,
    QualityInspectionCriteria,
)
from .phase19_customer_master_pricing import (
    Customer,
    CustomerBankAccount,
    CustomerContact,
    CustomerPriceList,
    CustomerPriceListItem,
)
from .phase20_receivables_delivery import (
    CustomerBalance,
    CustomerReceipt,
    CustomerTransaction,
    DeliveryOrder,
    DeliveryOrderLine,
)
from .phase21_hr_compliance_recruitment import (
    EmployeeCustody,
    EmployeeDocument,
    EmployeeViolation,
    JobApplication,
    JobOpening,
)
from .phase22_mfg_attachments_commissions import (
    Attachment,
    BillOfMaterial,
    BomOutput,
    CheckStatusLog,
    CommissionRule,
)
from .phase23_reporting_documents_fx_crm import (
    CrmContact,
    CurrencyTransaction,
    DocumentTemplate,
    DocumentType,
    FinancialReport,
)


target_metadata = ModelBase.metadata
MODELED_TABLES = set(target_metadata.tables.keys())

__all__ = [
    "ModelBase",
    "UserBranch",
    "PartyGroup",
    "Party",
    "TreasuryAccount",
    "Warehouse",
    "Invoice",
    "InvoiceLine",
    "CompanySetting",
    "CompanyUser",
    "Branch",
    "Account",
    "JournalEntry",
    "JournalLine",
    "ProductCategory",
    "ProductUnit",
    "Product",
    "Inventory",
    "InventoryTransaction",
    "StockAdjustment",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "PayrollPeriod",
    "Department",
    "EmployeePosition",
    "Employee",
    "Attendance",
    "EmployeeLoan",
    "LeaveRequest",
    "SalaryStructure",
    "SalaryComponent",
    "EmployeeSalaryComponent",
    "PayrollEntry",
    "TreasuryTransaction",
    "BankReconciliation",
    "BankStatementLine",
    "TaxRate",
    "TaxGroup",
    "TaxReturn",
    "TaxPayment",
    "TaxRegime",
    "BranchTaxSetting",
    "CompanyTaxSetting",
    "Project",
    "ProjectTask",
    "ProjectBudget",
    "ProjectExpense",
    "ProjectRevenue",
    "ProjectDocument",
    "ProjectChangeOrder",
    "CheckReceivable",
    "CheckPayable",
    "NoteReceivable",
    "NotePayable",
    "Expense",
    "ServiceRequest",
    "ServiceRequestCost",
    "Document",
    "DocumentVersion",
    "SupportTicket",
    "TicketComment",
    "ApprovalWorkflow",
    "ApprovalRequest",
    "ApprovalAction",
    "AssetCategory",
    "Asset",
    "AssetTransfer",
    "Budget",
    "BudgetItem",
    "BudgetLine",
    "CostCenter",
    "CostCenterBudget",
    "CostingPolicy",
    "CostingPolicyDetail",
    "CostingPolicyHistory",
    "InventoryCostSnapshot",
    "AssetDepreciationSchedule",
    "AssetDisposal",
    "AssetRevaluation",
    "AssetInsurance",
    "AssetMaintenance",
    "AssetImpairment",
    "Currency",
    "ExchangeRate",
    "BankImportBatch",
    "BankImportLine",
    "FiscalYear",
    "FiscalPeriodLock",
    "ZakatCalculation",
    "Contract",
    "ContractItem",
    "ExpensePolicy",
    "CrmLeadScoringRule",
    "CrmLeadScore",
    "CrmCustomerSegment",
    "CrmCustomerSegmentMember",
    "CrmSalesForecast",
    "ApiKey",
    "AuditLog",
    "BackupHistory",
    "CustomReport",
    "EmailTemplate",
    "BatchSerialMovement",
    "CycleCount",
    "CycleCountItem",
    "BinLocation",
    "BinInventory",
    "ProductAttribute",
    "ProductAttributeValue",
    "ProductVariant",
    "ProductVariantAttribute",
    "ProductKit",
    "ProductBatch",
    "ProductSerial",
    "QualityInspection",
    "QualityInspectionCriteria",
    "ProductKitItem",
    "Customer",
    "CustomerContact",
    "CustomerBankAccount",
    "CustomerPriceList",
    "CustomerPriceListItem",
    "CustomerTransaction",
    "CustomerReceipt",
    "CustomerBalance",
    "DeliveryOrder",
    "DeliveryOrderLine",
    "EmployeeDocument",
    "EmployeeViolation",
    "EmployeeCustody",
    "JobOpening",
    "JobApplication",
    "Attachment",
    "BillOfMaterial",
    "BomOutput",
    "CheckStatusLog",
    "CommissionRule",
    "FinancialReport",
    "DocumentType",
    "DocumentTemplate",
    "CurrencyTransaction",
    "CrmContact",
    "target_metadata",
    "MODELED_TABLES",
]
